/tracking/verbose 2 
/random/setSeeds 377 0 
/hvev/voltage 0 volt 
/g4cmp/produceCharges 1.0 
/g4cmp/producePhonons 1.0 
/g4cmp/sampleLuke 1.0 
/hvev/PrimaryParticleName Be7_KEC_ground 
/hvev/HitsRootFile /Users/yumiao/Documents/Works/SterileNeutrino/BeEST/Simulation/HVeV/build/test_Be7_KEC_ground_noVbias_seed0_10um
/hvev/PrimariesFlag true
/run/initialize 
/gps/number 1
/gps/pos/centre 0. 0. -1.99 mm
/run/beamOn 1
